[rule]
transformer.0.string.search = 'className'
transformer.0.string.replace = 'class'


# rule human description i18n
[languages]

[languages.en]
title = 'In JSX, replace `className` with `class`'
description = '''
Unlike in React, SolidJS doesn't need the weird `className` for the CSS styling. So, we can use the normal CSS `class` itself.
'''


[testcases]

[testcases.0]
test = 'className in style attribute gets replaced'

input = '''
const element = (
  <h1 className="greeting">
    Hello, world!
  </h1>
);
'''
# Expected output
output = '''
const element = <h1 class="greeting">
    Hello, world!
  </h1>;
'''

[testcases.1]
test = 'className in other parts are not affected'

input = '''
let className = 'menu';
'''
# Expected output
output = '''
let className = 'menu';
'''


[meta]
author = "@rrjanbiah" # GitHub username
# references
credits.0 = "https://www.youtube.com/watch?v=wu6HvLoi9VQ"
